-- 코드를 입력하세요
WITH BOOK_SALES_BY_BOOKID AS (
    SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS SALES
    FROM BOOK B
    JOIN (SELECT * FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%') S
        ON B.BOOK_ID = S.BOOK_ID
    JOIN AUTHOR A
        ON B.AUTHOR_ID = A.AUTHOR_ID
    GROUP BY B.BOOK_ID
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES_BY_BOOKID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC

# SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
# FROM BOOK B
# JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
# WHERE S.SALES_DATE LIKE '2022-01%'
# GROUP BY A.AUTHOR_ID, B.CATEGORY
# ORDER BY A.AUTHOR_ID, B.CATEGORY DESC