SELECT E.ID, COALESCE(C.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN (
SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA 
WHERE PARENT_ID IS NOT NULL
GROUP BY PARENT_ID) C ON E.ID = C.PARENT_ID