-- ONLINE_SALE 테이블
-- ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- 온라인 상품 판매 ID, 회원 ID, 상품 ID, 판매량, 판매일
-- OFFLINE_SALE 테이블
-- OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- 오프라인 상품 판매 ID, 상품 ID, 판매량, 판매일

SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM 
    (
    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
    )
    UNION
    (
    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT FROM OFFLINE_SALE 
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
    )
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC