-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT O.ANIMAL_ID, O.NAME, DATEDIFF(O.DATETIME, DATE_FORMAT(I.DATETIME, '%Y-%m-%d')) AS DD
    FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
    ORDER BY DD DESC
    LIMIT 2
) A