WITH CTE AS (
    SELECT ID,
           ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RN
    FROM ECOLI_DATA 
)

SELECT ID, CASE WHEN RN <= (COUNT(*) OVER() * 0.25) THEN 'CRITICAL'
                WHEN RN <= (COUNT(*) OVER() * 0.5) THEN 'HIGH'
                WHEN RN <= (COUNT(*) OVER() * 0.75) THEN 'MEDIUM'
           ELSE 'LOW' END AS COLONY_NAME
FROM CTE
ORDER BY ID

