-- 각 세대별 자식없는 개체수, 세대 출력. 세대별 오름차순. 
WITH RECURSIVE GEN_TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, T.GENERATION + 1 
    FROM ECOLI_DATA E
    INNER JOIN GEN_TREE T ON E.PARENT_ID = T.ID
)

SELECT COUNT(*) AS COUNT, GENERATION FROM GEN_TREE 
WHERE ID NOT IN (SELECT DISTINCT(PARENT_ID) FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION ASC
