# SELECT H.HISTORY_ID, CASE WHEN DAYS >= 90 THEN TRUNCATE(C.DAILY_FEE * (SELECT (100 - DISCOUNT_RATE) * 0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상') * DAYS, 0)
#                           WHEN DAYS >= 30 THEN TRUNCATE(C.DAILY_FEE * (SELECT (100 - DISCOUNT_RATE) * 0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상') * DAYS, 0)
#                           WHEN DAYS >= 7 THEN TRUNCATE(C.DAILY_FEE * (SELECT (100 - DISCOUNT_RATE) * 0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상') * DAYS, 0)
#                           ELSE C.DAILY_FEE * DAYS
#                      END AS FEE
# FROM (SELECT HISTORY_ID, CAR_ID, END_DATE - START_DATE + 1 AS DAYS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) H 
# JOIN (SELECT CAR_ID, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = '트럭') C ON H.CAR_ID = C.CAR_ID
# ORDER BY FEE DESC, HISTORY_ID DESC

SELECT H.HISTORY_ID,
       TRUNCATE(
           C.DAILY_FEE
           * H.DAYS
           * (100 - COALESCE(D.DISCOUNT_RATE, 0)) / 100,
           0
       ) AS FEE
FROM (
    SELECT HISTORY_ID,
           CAR_ID,
           DATEDIFF(END_DATE, START_DATE) + 1 AS DAYS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) H

JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
AND C.CAR_TYPE = '트럭'

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON D.CAR_TYPE = C.CAR_TYPE
AND D.DURATION_TYPE =
CASE
    WHEN H.DAYS >= 90 THEN '90일 이상'
    WHEN H.DAYS >= 30 THEN '30일 이상'
    WHEN H.DAYS >= 7 THEN '7일 이상'
END

ORDER BY FEE DESC, HISTORY_ID DESC;