-- 코드를 입력하세요
# SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR ASC

WITH 
RECURSIVE HOURS AS (
    SELECT 0 AS HOUR -- 시작점 (Anchor)
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23 -- 반복 조건
), 
ANIMALS AS (
    SELECT ANIMAL_ID, HOUR(DATETIME) AS HOUR FROM ANIMAL_OUTS
)

SELECT H.HOUR AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOURS H LEFT OUTER JOIN ANIMALS A ON H.HOUR = A.HOUR
GROUP BY H.HOUR
