-- MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH
-- 회원 ID, 회원 이름, 회원 연락처, 성별, 생년월일
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH, 'MM') = '03'
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC