WITH MAXCNT AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT 
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
FROM REST_REVIEW R 
JOIN MAXCNT C ON R.MEMBER_ID = C.MEMBER_ID
JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
WHERE C.CNT = (SELECT MAX(CNT) FROM MAXCNT)
ORDER BY REVIEW_DATE, REVIEW_TEXT